import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#3366cc",
        "outline-variant": "#c3c6d5",
        "on-error-container": "#93000a",
        "secondary-fixed": "#dfe3e8",
        "tertiary-fixed": "#f9e37a",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#303031",
        "error": "#ba1a1a",
        "background": "#faf9fa",
        "surface-variant": "#e3e2e3",
        "on-secondary-fixed": "#171c20",
        "on-tertiary-fixed": "#211b00",
        "surface-container-highest": "#e3e2e3",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#4a3f00",
        "on-primary-fixed": "#001946",
        "on-secondary-container": "#606569",
        "error-container": "#ffdad6",
        "secondary": "#5a5f63",
        "on-primary-container": "#e7ebff",
        "surface": "#faf9fa",
        "secondary-fixed-dim": "#c2c7cc",
        "tertiary": "#6d5e00",
        "inverse-primary": "#b1c5ff",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dbdadb",
        "primary-fixed": "#d9e2ff",
        "outline": "#737784",
        "on-primary-fixed-variant": "#00419d",
        "tertiary-fixed-dim": "#dcc661",
        "on-surface-variant": "#434653",
        "surface-container-low": "#f5f3f4",
        "secondary-container": "#dfe3e8",
        "inverse-on-surface": "#f2f0f1",
        "primary-fixed-dim": "#b1c5ff",
        "on-background": "#1b1c1d",
        "surface-tint": "#2259bf",
        "on-secondary": "#ffffff",
        "surface-container": "#efedee",
        "surface-container-high": "#e9e8e9",
        "surface-bright": "#faf9fa",
        "on-tertiary-fixed-variant": "#524600",
        "tertiary-container": "#bfab49",
        "on-secondary-fixed-variant": "#42474b",
        "primary": "#094cb2",
        "on-surface": "#1b1c1d"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "md": "0.75rem"
      },
      fontFamily: {
        headline: ["'Noto Serif'", "serif"],
        display: ["'Noto Serif'", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["'Public Sans'", "sans-serif"],
        serif: ["'Noto Serif'", "serif"],
        sans: ["Inter", "sans-serif"],
      },
      boxShadow: {
        'glass': '0 4px 30px rgba(0, 0, 0, 0.05)',
        'modal': '0 24px 40px rgba(27, 28, 29, 0.06)',
      }
    },
  },
  plugins: [],
};
export default config;
